Create neymanPearson2.py
probml/pyprobml pull request #302
Opened 2021-03-20 17:29 UTC by Garvit9000c

![index](https://user-images.githubusercontent.com/68856476/111880130-8eaefb80-89cf-11eb-8645-18ee37aa27db.png)

The Only Difference is , alpha and beta region are shaded continuously instead of Multiple consecutive Lines.

2021-03-20 18:05 UTC, mjsML commented
Please mention issue number like closes #185

2021-03-20 18:07 UTC, mjsML approved these changes
use matpplotlib to render labels properly as per their [documentation](https://matplotlib.org/stable/tutorials/text/mathtext.html)

2021-03-21 00:48 UTC, Garvit9000c commented
Ohk Sir, 
Now on will remember these two points.
*Linking the issue with pull request
*Using proper matplotlib annotation to render mathematical expressions.

2021-03-21 23:37 UTC, murphyk requested changes
There is no need to use jax for such a simple example. Please rewrite to use vanilla numpy/scipy.

2021-03-22 03:12 UTC, Garvit9000c commented
OK Sir

2021-03-22 05:42 UTC, merged