Converted gaussImputationDemo to python
probml/pyprobml pull request #339
Opened 2021-04-07 11:48 UTC by shivaditya-meduri

![Hinton_Observed](https://user-images.githubusercontent.com/77324692/113861704-ca0b4180-97a7-11eb-90d3-ca49cd935807.png)
![Hinton_Truth](https://user-images.githubusercontent.com/77324692/113861709-caa3d800-97a7-11eb-9445-574e614453fe.png)
![Hinton_ImputationWithTrueParams](https://user-images.githubusercontent.com/77324692/113861710-caa3d800-97a7-11eb-98c6-ce655fe68761.png)

Closes #171 

I implemented gauss Imputation basing it on gaussImpute() and gaussCondition() matlab files in pmtk3.googlecode.com. 

To randomly create sigma, I have used the sci-kit learn library instead of implementing randpd because of the excessive time delay in creating a positive semidefinite matrix as the probability of creating one SPD using randpd in python is less than 1.

Please note that the MATLAB implementation has randomly generated a matrix of size 20x10 but in the book I observed that a matrix of 8x10 is provided, therefore I provided the inputs d=8 and n=10, but the dimensions of the matrix can be changed by altering n & d in the code.

2021-04-07 11:49 UTC, shivaditya-meduri commented
@mjsML, @murphyk 
Please review this PR

2021-04-07 13:53 UTC, mjsML approved these changes

2021-04-07 13:54 UTC, mjsML commented
I updated the colors, please update the screenshots based on the new colors :)

2021-04-09 16:23 UTC, murphyk requested changes
- please use longer, more readable variable names, and follow [PEP8 conventions](https://www.python.org/dev/peps/pep-0008/#function-and-variable-names), even if this differs from the matlab.
- please vectorize your code! eg to extract the hidden entries of the Sigma matrix and assign to the Sh matrix, you can use [fancy indexing](https://jakevdp.github.io/PythonDataScienceHandbook/02.07-fancy-indexing.html) to do it in parallel.
- please rename hinton to `hinton_diagram` and submit this as a separate, standalone PR. 
-

2021-04-09 16:52 UTC, murphyk commented
Here is an example of how extract a block submatrix.
First make the matrix
```
import numpy as np
X = np.arange(12).reshape((3, 4))
print(X)
row = np.array([0,  2])
col = np.array([0, 2, 3])
```
Here is the slow for-loop version:
```
X2 = np.zeros([len(row), len(col)])
for itarget, isrc in enumerate(row):
  for jtarget, jsrc in enumerate(col):
    X2[itarget, jtarget]  = X[isrc, jsrc]
print(X2)
```
Here is the preferred vectorized version
```
ndx = np.ix_(row, col)
X2 = X[ndx]
print(X2.shape) # (2,3)
print(X2)
```

2021-04-09 18:09 UTC, murphyk commented
It seems that [hinton_diagram](https://github.com/probml/pyprobml/blob/master/scripts/hinton_diagram.py) is already in pyprobml, so you can just import that and use it, rather than duplicating code.

2021-04-10 16:44 UTC, shivaditya-meduri commented
Hi @murphyk , I observed that the hinton_diagram.py has a few deprecated methods in the code and I created a pull request that will fix the bug.
The color schematic of hinton_diagram.py file is restricted to black and white, and the images in the book are colored differently, 
can you please confirm if the colors of the positive and the negative elements of the matrix can be black and white?

2021-04-10 18:13 UTC, closed without merging