Converted mixBerMnistEM to python
probml/pyprobml pull request #340
Opened 2021-04-07 14:43 UTC by shivaditya-meduri

![mixBernoulliMnist](https://user-images.githubusercontent.com/77324692/113885700-532e7280-97c0-11eb-9abd-32ec04588c3f.png)
Closes #174

The code might take some time to load and this is because it is downloading the MNIST dataset from online and the delay in execution is solely due to this and not due to the inefficiency of the code.

The values and the images will differ because the data is randomly chosen from the total set of images.

I initially added +1 to all images in the training set and changed the Bernoulli function to adapt to this, but did not see any change in the execution, It was more convenient for me to use the binary image as is and use the implementation of Bernoulli distribution which is used for this mixture model.

In this implementation, I did not find the optimal k because the optimal k=20 has already been found through trial and error in the MATLAB code and no graph implementation is found in the book.

2021-04-07 14:44 UTC, shivaditya-meduri commented
@mjsML, Thank you for your suggestion, I've created a new pullrequest

2021-04-07 15:23 UTC, mjsML approved these changes

2021-04-09 16:15 UTC, murphyk requested changes
- Please vectorize all your code where possible. For example, never write `for i=1:N`! (Obviously EM iterations are sequential, and it's probably ok to loop over k=1:K, but not over data points.)
- replace your `bernoulli` function with https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.bernoulli.html
- factor out the code that does parameter initialization and image plotting into subfunctions, to simplify main() 
- I find fetch_openml to be slow for getting MNIST. You may find the pytorch.vision dataloader, or the tensorflow datasets version, faster (both libraries are built in to colab).

2021-04-11 05:10 UTC, shivaditya-meduri commented
I made a new PR with only 1 commit, Please find it here : https://github.com/probml/pyprobml/pull/344

2021-04-11 05:10 UTC, closed without merging