Create binary_fa_demo.py
probml/pyprobml pull request #445
Opened 2021-04-28 21:08 UTC by karalleyna

Closes #231 

I have attained Figure 20.14 in the book. Could you please review it? @murphyk @mjsML
 
![1](https://user-images.githubusercontent.com/36455180/116472179-3a285700-a87e-11eb-9d43-e11202ddc73a.png)
![2](https://user-images.githubusercontent.com/36455180/116472184-3b598400-a87e-11eb-8698-293751579b08.png)
![3](https://user-images.githubusercontent.com/36455180/116472187-3bf21a80-a87e-11eb-8f8b-ec825c575304.png)
![4](https://user-images.githubusercontent.com/36455180/116472188-3c8ab100-a87e-11eb-8f6e-d99cfbcee613.png)

2021-04-30 02:15 UTC, murphyk requested changes
Looks good, but you forgot to add the `sigmoid_times_gauss` function

2021-04-30 08:23 UTC, karalleyna commented
Thank you @murphyk. I added sigmoid_times_gauss function.

2021-05-04 04:44 UTC, murphyk requested changes
Please can you replace the for-loop in sigmoid-times-gauss wth jax.vmap :)

2021-05-12 04:05 UTC, murphyk commented
LGTM, thanks!

2021-05-12 04:05 UTC, merged